stages:
  - test
  - deploy

#Before script
#before_script:
  # - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # - sudo apt-get install -y nodejs

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

run_tests:
  stage: test
  script:
    #- npm install --silent -q
    #- npm run lint
    #- npm test
    - echo 'hello'

run_deploy:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - cd .. && tar -cvf webapps_29.tar ./webapps_29
    - scp webapps_29.tar rm3115@146.169.45.133:/home/rm3115/webapps_29.tar
    - ssh -K rm3115@146.169.45.133
    - pm2 stop all
    - cd /home/rm3115 && rm -rf webapps_29 && tar -xvf webapps_29.tar
    - cd webapps_29 && npm install && pm2 start server.js
  only:
    - master
